services:
  n8n:
    image: ${N8N_IMAGE:-n8nio/n8n:latest}
    restart: ${N8N_RESTART_POLICY:-always}
    ports:
      - "${N8N_BIND_PORT:-5678}:${N8N_PORT:-5678}"
    extra_hosts:
      - "host.docker.internal:${HOST_DOCKER_INTERNAL_IP}"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      N8N_HOST: ${N8N_HOST}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-https}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PATH: ${N8N_PATH:-/n8n/}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-America/Sao_Paulo}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE:-true}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}

    volumes:
      - ./data:/home/node/.n8n
